import { CallContact, CreatorSocials } from '../types';

export const UMANG_RAI_SOCIALS: CreatorSocials = {
  name: 'Umang Rai',
  instagram: {
    handle: '@ur_umang_rai',
    url: 'https://instagram.com/ur_umang_rai',
  },
  discord: {
    handle: '@hardikrai78',
    tag: 'hardikrai78',
  },
  youtube: {
    handle: '@lunarhardikyt',
    url: 'https://youtube.com/@lunarhardikyt',
  },
};

export const INITIAL_CALL_CONTACTS: CallContact[] = [
  {
    id: 'umang-rai',
    name: 'Umang Rai',
    roleOrTitle: 'Master Architect & Creator',
    handleOrNumber: '@ur_umang_rai (Quantum Direct)',
    category: 'core',
    avatarGradient: 'from-[#ff2d55] to-[#ff9500]',
    status: 'online',
    isFavorite: true,
  },
  {
    id: 'tony-stark',
    name: 'Tony Stark',
    roleOrTitle: 'Stark Industries Founder',
    handleOrNumber: '+1 (212) 555-STARK',
    category: 'avengers',
    avatarGradient: 'from-[#00e5ff] to-[#0284c7]',
    status: 'online',
    isFavorite: true,
  },
  {
    id: 'pepper-potts',
    name: 'Pepper Potts',
    roleOrTitle: 'CEO, Stark Industries',
    handleOrNumber: 'pepper@starkindustries.com',
    category: 'core',
    avatarGradient: 'from-[#ec4899] to-[#f43f5e]',
    status: 'online',
    isFavorite: true,
  },
  {
    id: 'peter-parker',
    name: 'Peter Parker',
    roleOrTitle: 'Spider-Man / Queens Ops',
    handleOrNumber: 'Spidey Comms Channel 4',
    category: 'avengers',
    avatarGradient: 'from-[#ef4444] to-[#3b82f6]',
    status: 'online',
    isFavorite: true,
  },
  {
    id: 'bruce-banner',
    name: 'Dr. Bruce Banner',
    roleOrTitle: 'Gamma Physics & Bio Lab',
    handleOrNumber: 'banner-lab-secure-grid',
    category: 'avengers',
    avatarGradient: 'from-[#10b981] to-[#059669]',
    status: 'online',
    isFavorite: false,
  },
  {
    id: 'nick-fury',
    name: 'Nick Fury',
    roleOrTitle: 'Director of S.H.I.E.L.D.',
    handleOrNumber: 'ENCRYPTED-LEVEL-10-LINE',
    category: 'vip',
    avatarGradient: 'from-[#64748b] to-[#1e293b]',
    status: 'encrypted',
    isFavorite: false,
  },
  {
    id: 'thor',
    name: 'Thor Odinson',
    roleOrTitle: 'Bifrost Tactical Comm',
    handleOrNumber: 'Asgard-Cosmic-Relay',
    category: 'avengers',
    avatarGradient: 'from-[#fbbf24] to-[#d97706]',
    status: 'online',
    isFavorite: false,
  },
  {
    id: 'satellite-defense',
    name: 'Satellite Defense Hotline',
    roleOrTitle: 'Orbital Defense Matrix',
    handleOrNumber: 'SAT-990-ORBITAL',
    category: 'vip',
    avatarGradient: 'from-[#a855f7] to-[#6366f1]',
    status: 'online',
    isFavorite: false,
  },
];
